In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Pandas:", pd.__version__)
print("Success!")

Pandas: 3.0.3
Success!

In [6]:
with open("houses/cadata.txt", "r", encoding="latin1") as f:
    for i in range(40):
        print(i, f.readline())

0 S&P Letters Data

1 We collected information on the variables using all the block groups in California from the 1990 Census. In this sample a block group on average includes 1425.5 individuals living in a geographically compact area. Naturally, the geographical area included varies inversely with the population density. We computed distances among the centroids of each block group as measured in latitude and longitude. We excluded all the block groups reporting zero entries for the independent and dependent variables. The final data contained 20,640 observations on 9 variables. The dependent variable is ln(median house value).

2

3 		Bols	tols

4 INTERCEPT		11.4939	275.7518

5 MEDIAN INCOME		0.4790	45.7768

6 MEDIAN INCOME2		-0.0166	-9.4841

7 MEDIAN INCOME3		-0.0002	-1.9157

8 ln(MEDIAN AGE)		0.1570	33.6123

9 ln(TOTAL ROOMS/ POPULATION)	-0.8582	-56.1280

10 ln(BEDROOMS/ POPULATION)	0.8043	38.0685

11 ln(POPULATION/ HOUSEHOLDS)	-0.4077	-20.8762

12 ln(HOUSEHOLDS)		0.0477	13.0792

13

14 The file cadata.txt contains all the the variables. Specifically, it contains median house value, median income, housing median age, total rooms, total bedrooms, population, households, latitude, and longitude in that order.

15

16 Reference

17

18 Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions, Statistics and Probability Letters, 33 (1997) 291-297.

19

20 The manuscript describing the data can be found at www.spatial-statistics.com. The data are also

21 available as Matlab files.

22

23 Contact kelley@spatial-statistics.com or kelley@pace.am if you have any further questions. Thanks.

24

25

26

27   4.5260000000000000e+005  8.3252000000000006e+000  4.1000000000000000e+001  8.8000000000000000e+002  1.2900000000000000e+002  3.2200000000000000e+002  1.2600000000000000e+002  3.7880000000000003e+001 -1.2223000000000000e+002

28   3.5850000000000000e+005  8.3013999999999992e+000  2.1000000000000000e+001  7.0990000000000000e+003  1.1060000000000000e+003  2.4010000000000000e+003  1.1380000000000000e+003  3.7859999999999999e+001 -1.2222000000000000e+002

29   3.5210000000000000e+005  7.2573999999999996e+000  5.2000000000000000e+001  1.4670000000000000e+003  1.9000000000000000e+002  4.9600000000000000e+002  1.7700000000000000e+002  3.7850000000000001e+001 -1.2223999999999999e+002

30   3.4130000000000000e+005  5.6430999999999996e+000  5.2000000000000000e+001  1.2740000000000000e+003  2.3500000000000000e+002  5.5800000000000000e+002  2.1900000000000000e+002  3.7850000000000001e+001 -1.2225000000000000e+002

31   3.4220000000000000e+005  3.8462000000000001e+000  5.2000000000000000e+001  1.6270000000000000e+003  2.8000000000000000e+002  5.6500000000000000e+002  2.5900000000000000e+002  3.7850000000000001e+001 -1.2225000000000000e+002

32   2.6970000000000000e+005  4.0368000000000004e+000  5.2000000000000000e+001  9.1900000000000000e+002  2.1300000000000000e+002  4.1300000000000000e+002  1.9300000000000000e+002  3.7850000000000001e+001 -1.2225000000000000e+002

33   2.9920000000000000e+005  3.6591000000000000e+000  5.2000000000000000e+001  2.5350000000000000e+003  4.8900000000000000e+002  1.0940000000000000e+003  5.1400000000000000e+002  3.7840000000000003e+001 -1.2225000000000000e+002

34   2.4140000000000000e+005  3.1200000000000001e+000  5.2000000000000000e+001  3.1040000000000000e+003  6.8700000000000000e+002  1.1570000000000000e+003  6.4700000000000000e+002  3.7840000000000003e+001 -1.2225000000000000e+002

35   2.2670000000000000e+005  2.0804000000000000e+000  4.2000000000000000e+001  2.5550000000000000e+003  6.6500000000000000e+002  1.2060000000000000e+003  5.9500000000000000e+002  3.7840000000000003e+001 -1.2226000000000001e+002

36   2.6110000000000000e+005  3.6911999999999998e+000  5.2000000000000000e+001  3.5490000000000000e+003  7.0700000000000000e+002  1.5510000000000000e+003  7.1400000000000000e+002  3.7840000000000003e+001 -1.2225000000000000e+002

37   2.8150000000000000e+005  3.2031000000000001e+000  5.2000000000000000e+001  2.2020000000000000e+003  4.3400000000000000e+002  9.1000000000000000e+002  4.0200000000000000e+002  3.7850000000000001e+001 -1.2226000000000001e+002

38   2.4180000000000000e+005  3.2705000000000002e+000  5.2000000000000000e+001  3.5030000000000000e+003  7.5200000000000000e+002  1.5040000000000000e+003  7.3400000000000000e+002  3.7850000000000001e+001 -1.2226000000000001e+002

39   2.1350000000000000e+005  3.0750000000000002e+000  5.2000000000000000e+001  2.4910000000000000e+003  4.7400000000000000e+002  1.0980000000000000e+003  4.6800000000000000e+002  3.7850000000000001e+001 -1.2226000000000001e+002

In [7]:
import pandas as pd

columns = [
    "MedHouseVal",
    "MedInc",
    "HouseAge",
    "TotalRooms",
    "TotalBedrooms",
    "Population",
    "Households",
    "Latitude",
    "Longitude"
]

df = pd.read_csv(
    "houses/cadata.txt",
    sep=r"\s+",
    skiprows=32,
    header=None,
    names=columns,
    encoding="latin1"
)

df.head()

,MedHouseVal,MedInc,HouseAge,TotalRooms,TotalBedrooms,Population,Households,Latitude,Longitude
0,269700.0,4.0368,52.0,919.0,213.0,413.0,193.0,37.85,-122.25
1,299200.0,3.6591,52.0,2535.0,489.0,1094.0,514.0,37.84,-122.25
2,241400.0,3.1200,52.0,3104.0,687.0,1157.0,647.0,37.84,-122.25
3,226700.0,2.0804,42.0,2555.0,665.0,1206.0,595.0,37.84,-122.26
4,261100.0,3.6912,52.0,3549.0,707.0,1551.0,714.0,37.84,-122.25

In [8]:
df.shape

(20635, 9)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20635 entries, 0 to 20634
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MedHouseVal    20635 non-null  float64
 1   MedInc         20635 non-null  float64
 2   HouseAge       20635 non-null  float64
 3   TotalRooms     20635 non-null  float64
 4   TotalBedrooms  20635 non-null  float64
 5   Population     20635 non-null  float64
 6   Households     20635 non-null  float64
 7   Latitude       20635 non-null  float64
 8   Longitude      20635 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [10]:
df.describe()

,MedHouseVal,MedInc,HouseAge,TotalRooms,TotalBedrooms,Population,Households,Latitude,Longitude
count,20635.000000,20635.000000,20635.000000,20635.000000,20635.000000,20635.000000,20635.000000,20635.000000,20635.000000
mean,206816.445893,3.869992,28.635861,2635.803392,537.934335,1425.611728,499.567725,35.631322,-119.569058
std,115380.007032,1.899362,12.583523,2181.576998,421.254693,1132.502473,382.326147,2.135930,2.003344
min,14999.000000,0.499900,1.000000,2.000000,1.000000,3.000000,1.000000,32.540000,-124.350000
25%,119600.000000,2.562500,18.000000,1448.000000,296.000000,787.000000,280.000000,33.930000,-121.800000
50%,179700.000000,3.534500,29.000000,2127.000000,435.000000,1166.000000,409.000000,34.260000,-118.490000
75%,264700.000000,4.742600,37.000000,3148.000000,647.000000,1725.000000,605.000000,37.710000,-118.010000
max,500001.000000,15.000100,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,41.950000,-114.310000

In [11]:
df.isnull().sum()

MedHouseVal      0
MedInc           0
HouseAge         0
TotalRooms       0
TotalBedrooms    0
Population       0
Households       0
Latitude         0
Longitude        0
dtype: int64